const CARDS_COUNT_PER_STEP = 5;
const CARDS_COUNT = 23;
const CARDS_TOP_COUNT = 2;

const SORT_TYPE = {
  DEFAULT: 'DEFAULT',
  DATE: 'DATE',
  RATING: 'RATING',
};

export {CARDS_COUNT_PER_STEP, CARDS_COUNT, SORT_TYPE};
