const CARDS_COUNT_PER_STEP = 5;
const CARDS_COUNT = 23;
const CARDS_TOP_COUNT = 2;

const SORT_TYPE = {
  DEFAULT: 'DEFAULT',
  DATE: 'DATE',
  RATING: 'RATING',
};

const EMOTIONS = {
  SMILE: 'smile',
  SLEEPING: 'sleeping',
  PUKE:'puke',
  ANGRY: 'angry',
};

const USER_ACTION = {
  UPDATE_FILM: 'UPDATE_FILM',
};

const UPDATE_TYPE = {
  PATCH: 'PATCH',
  MINOR: 'MINOR',
  MAJOR: 'MAJOR',
};

const FILTER_TYPE = {
  WATCHLIST: 'WATCHLIST',
  HISTORY: 'HISTORY',
  FAVORITES: 'FAVORITES',
};
export {CARDS_COUNT_PER_STEP, CARDS_COUNT, SORT_TYPE, EMOTIONS, USER_ACTION, UPDATE_TYPE, FILTER_TYPE};
